Add identity profile image
holaplex/hub-identities pull request #20
Opened 2023-05-08 11:37 UTC by alchemistgo87

2023-05-08 11:51 UTC, kespinola requested changes

2023-05-08 11:51 UTC, kespinola commented on kratos/identity.schema.json
> +        "profileImage": {
```suggestion
        "profile_image": {
```

2023-05-08 11:51 UTC, kespinola commented on api/src/graphql/objects/user.rs
> +            profile_image: profile_image.unwrap_or_default(),
The graphql type can be Option<String> so don't need to unwrap to an empty string. null more descriptive on it not being set.

2023-05-08 15:00 UTC, mpwsh approved these changes

2023-05-10 16:15 UTC, kespinola approved these changes

2023-05-10 16:15 UTC, merged